"use client"
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { useRouter } from "next/navigation";

export const metadata = {
    title: 'NextNinja | Blogs',
    description: 'Generated by Next.js',
}

const blogs = [
    {
        id: 1,
        year: 2015,
        title: "Learn React Js",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
    },
    {
        id: 2,
        year: 2016,
        title: "Learn Next Js",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
    },
    {
        id: 3,
        year: 2017,
        title: "Learn Typescript",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
    },
    {
        id: 4,
        year: 2018,
        title: "Learn Redix UI",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
    }
]

const BlogsPage = () => {
    const router = useRouter();
    return (
        <div>
            <h1 className="font-bold text-3xl text-center my-10">Read our popular blogs</h1>
            <div className="grid grid-cols-2 gap-4">
                {
                    blogs.map(({ id, year, title, description }) => (
                        <div className="p-4 border flex flex-col gap-4" key={id}>
                            <h2 className="font-bold text-xl">{title}</h2>
                            <p>Published: {year}</p>
                            <p><span className="font-bold">Description:</span> {description}</p>
                            <Button onClick={() => router.push(`/blogs/${year}/${id}?title=${title}`)} >
                                Details
                                {/* <Link href={{
                                    pathname: `/blogs/${year}/${id}`,
                                    query: {
                                        title: title
                                    }
                                }}>Read More..</Link> */}
                            </Button>
                        </div>
                    ))
                }
            </div>
        </div>
    );
};

export default BlogsPage;