import Sidebar from "@/components/SideBar/Sidebar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const layout = ({ children }) => {
  return (
    <div className="container mx-auto flex gap-4">
      <div>
        <Sidebar></Sidebar>
      </div>
      <div>
        {children}
      </div>
    </div>
  );
};

export default layout;
